### ISSUE TITLE
Migration from Mandrill

### ISSUE THREAD

**Issue by yepher** [bevacqua/campaign#11]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

**Comment by richleland** [comment]
Looks like we could pretty easily make a provider for Campaign for SparkPost.

**Comment by bevacqua** [comment]
That'd be awesome guys. Would definitely help adoption

**Comment by colestrode** [comment]
@bevacqua I'm started working on a SparkPost provider this afternoon. What's the best way to be in touch if I have questions? Another issue? Keep going on this thread? Messenger ponies? :)

**Comment by bevacqua** [comment]
Here probably, or create a repo and ping me

**Comment by colestrode** [comment]
Cool, I created a private repo and added you as a collaborator. I'll publish it once I get it fully functional
