### ISSUE TITLE
FEATURE: Localization

### ISSUE THREAD

**Issue by tiblu** [bevacqua/campaign#7]
It would be nice to have localization support so I could send out e-mails in different languages.

To consider:
* message body localization
* subject localization
* date and time formats...

Right now I implemented custom template reading  and parsing myself and use ``client.sendString``.

But what if we wanted to Campaign to provide it out of the box?

How would you approach localization in the Campaign @bevacqua ?

**Comment by bevacqua** [comment]
You're welcome to do this. I don't have the time

**Comment by tiblu** [comment]
@bevacqua I understand the time issue, just wanted your idea how and where would it fit in in the current codebase.
If no time for that either, its OK.
